export enum CustomRichTextType {
  HomePage = 1,
  Contact = 2,
  FrequentlyAskedQuestions = 3,
  AboutGET = 4,
  Disclaimer = 5,
  PlatformOverview = 6,
  MeasuringWaterUse = 7,
  ConfigureWaterTypes = 8,
  CreateWaterTransactions = 9,
  TrainingVideos = 10,
  CreateUserProfile = 11,
  CreateUserProfileStepOne = 12,
  CreateUserProfileStepTwo = 13,
  CreateUserProfileStepThree = 14,
  WaterAccountsAdd = 15,
  WaterAccountsAddLegalText = 16,
  WaterAccountsInvite = 17,
  ParcelList = 18,
  OpenETIntegration = 19,
  ParcelUpdateLayer = 20,
  InactiveParcelList = 21,
  AccountReconciliationReport = 22,
  ParcelLedgerCreate = 23,
  ParcelLedgerBulkCreate = 24,
  ParcelLedgerCreateFromSpreadsheet = 25,
  WebsiteFooter = 26
}