export enum CustomerType {
    Individual = "Individual",
    Corporation = "Corporation",
    MultiIndividual = "Multi-Individual",
    LimitedLiabilityCorporation = "Limited Liability Corporation",
    Other = "Other",
    Trust = "Trust",
    Partnership = "Partnership",
    LimitedPartnership = "Limited Partnership",
    Federal = "Federal",
    Unknown = "Unknown",
    LimitedLiabilityPartnership = "Limited Liability Partnership",
    State = "State",
    JointVenture = "Joint Venture",
    GrazingAssoc = "Grazing Assoc",
    SoleProprietorship = "Sole Proprietorship",
    GrazingDist = "Grazing Dist",
    ExemptOwner = "Exempt Owner",
    LegacyCustomerType1 = "Legacy Customer Type 1",
    LegacyCustomerType2 = "Legacy Customer Type 2",
    LegacyCustomerType4 = "Legacy Customer Type 4",
    LegacyCustomerType3 = "Legacy Customer Type 3",
    LegacyCustomerType9 = "Legacy Customer Type 9",
    LegacyCustomerType8 = "Legacy Customer Type 8",
    LegacyCustomerType5 = "Legacy Customer Type 5",
    LegacyCustomerType6 = "Legacy Customer Type 6",
    LegacyCustomerType7 = "Legacy Customer Type 7"
}