version: '3.7'

services:
  rio.web:
    image: sitkacontainers.azurecr.io/edf/web
    build:
      args:
        env: ${ENVIRONMENT}
      context: ../..
      dockerfile: Rio.Web/Dockerfile