version: '3.7'

services:
  rio.web:
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    image: sitkacontainers.azurecr.io/rio/web
    ports:
      - "8787:80"
      - "8786:443"
