apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rio-web.fullname" . }}-qa-configmap
data:
  ASPNETCORE_ENVIRONMENT: "Staging"
  Production: "false"
  Staging: "true"
  Dev: "false"
  MainAppApiUrl: "https://{{ .Values.global.domains.api }}"
  CreateAccountRedirectUrl: "https://{{ .Values.global.domains.web }}/create-user-callback"
  KeystoneSupportBaseUrl: "https://identity-qa.sitkatech.com/Authentication"
  GeoserverMapServiceUrl: "https://{{ .Values.global.domains.geoserver }}/geoserver/Rio"
  Keystone_ClientID: "{{ .Values.global.env.keystoneClientID }}"
  Keystone_Issuer: "https://identity-qa.sitkatech.com"
  Keystone_RedirectUriRelative: "/signin-oidc"
  Keystone_Scope: "openid profile offline_access keystone"
  Keystone_SessionCheckEnabled: "false"
  Keystone_LogoutUrl: "https://identity-qa.sitkatech.com/account/logout"
  Keystone_PostLogoutRedirectUri: "/"
  Keystone_WaitForTokenInMsec: "500"
  Keystone_ResponseType: "code"
  Keystone_DisablePKCE: "false"  