{{ if eq .Values.global.env.tenantName "rrb" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "web.fullname" . }}-rrb-configmap
data:
  allowTrading: "false"
  allowOpenETSync: "false"
  includeWaterSupply: "true"
  platformLongName: "Rosedale-Rio Bravo Water Accounting Platform"
  platformShortName: "Water Accounting Platform"
  leadOrganizationLongName: "Rosedale-Rio Bravo Water Storage District"
  leadOrganizationShortName: "RRB"
  leadOrganizationHomeUrl: "https://rrbwsd.com"
  faviconFilename: "rio_favicon.png"
  leadOrganizationLogoFilename: "rrbwsd_logo.jpg"
  navThemeColor: "white"
  homepageBannerFilename: "/assets/main/home_image.jpg"
  applicationInternalName: "{{ .Values.global.env.tenantName }}"
  parcelBoundingBoxLeft: "-119.45272037350193"
  parcelBoundingBoxRight: "-119.11015104115182"
  parcelBoundingBoxTop: "35.442022035628575"
  parcelBoundingBoxBottom: "35.27608156273151"
  enabledGETIntegration: "false"
  datadogClientToken: "pub083a61c0ce87f2d49aff26114600b3e4"
{{ end }}