apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rio-api.fullname" . }}-qa-configmap
data:
  SECRET_PATH: "/app/secrets/rioApiSecrets"
  DOCKER_BUILD_SOURCE: "."
  ASPNETCORE_ENVIRONMENT: "Staging"
  KEYSTONE_HOST: "https://identity-qa.sitkatech.com"
  SITKA_EMAIL_REDIRECT: "notifications-qa@sitkatech.com"
  WEB_URL: "https://{{ .Values.global.domains.web }}"
  KEYSTONE_REDIRECT_URL: "https://{{ .Values.global.domains.web }}/create-user-callback"
  APPINSIGHTS_INSTRUMENTATIONKEY: "{{ .Values.global.env.appInsightsInstrumentationKey }}"
  ALLOW_TRADING: "{{ .Values.global.env.allowTrading }}"
  PlatformLongName: "{{ .Values.global.env.platformLongName }}"
  PlatformShortName: "{{ .Values.global.env.platformShortName }}"
  LeadOrganizationLongName: "{{ .Values.global.env.leadOrganizationLongName }}"
  LeadOrganizationShortName: "{{ .Values.global.env.leadOrganizationShortName }}"
  LeadOrganizationHomeUrl: "{{ .Values.global.env.leadOrganizationHomeUrl }}"
  LeadOrganizationEmail: "{{ .Values.global.env.leadOrganizationEmail }}"
  VerificationKeyChars: "ABCDEFGHIJKLMNOPQRSTUVWXYZ,0123456789"
  ValidParcelNumberRegexPattern: "{{ .Values.global.env.validParcelNumberRegexPattern }}"
  ValidParcelNumberPatternAsStringForDisplay: "{{ .Values.global.env.validParcelNumberPatternAsStringForDisplay }}"
  OpenETAPIBaseUrl: "https://openet.dri.edu"
  OpenETRasterTimeSeriesMultipolygonRoute: "raster/timeseries/multipolygon"
  OpenETRasterMetadataRoute: "raster/metadata"
  OpenETAllFilesReadyForExportRoute: "raster/export/all_files"
  OpenETRasterExportStatusRoute: "raster/export/status"
  ParcelBoundingBoxLeft: "{{ .Values.global.env.parcelBoundingBoxLeft }}"
  ParcelBoundingBoxRight: "{{ .Values.global.env.parcelBoundingBoxRight }}"
  ParcelBoundingBoxTop: "{{ .Values.global.env.parcelBoundingBoxTop }}"
  ParcelBoundingBoxBottom: "{{ .Values.global.env.parcelBoundingBoxBottom }}"
  OpenETRasterTimeseriesMultipolygonColumnToUseAsIdentifier: "{{ .Values.global.env.openETRasterTimeseriesMultipolygonColumnToUseAsIdentifier }}"
  AllowOpenETSync: "{{ .Values.global.env.allowOpenETSync }}"
  Ogr2OgrExecutable: "/usr/bin/ogr2ogr"
  OgrInfoExecutable: "/usr/bin/ogrinfo"
