{{ if eq .Values.global.env.tenantName "edf" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api.fullname" . }}-edf-configmap
data:
  AllowTrading: "true"
  AllowOpenETSync: "false"
  IncludeWaterSupply: "true"
  PlatformLongName: "Environmental Defense Fund Water Accounting and Trading Platform"
  PlatformShortName: "Water Accounting and Trading Platform"
  LeadOrganizationLongName: "Environmental Defense Fund"
  LeadOrganizationShortName: "EDF"
  LeadOrganizationHomeUrl: "https://edf.org"
  LeadOrganizationEmail: "mriveratorres@edf.org"
  VerificationKeyChars: "ABCDEFGHIJKLMNOPQRSTUVWXYZ,0123456789"
  ValidParcelNumberRegexPattern: "^[0-9]{3}-[0-9]{2}-[0-9]{3}$$"
  ValidParcelNumberPatternAsStringForDisplay: "###-##-###"
  OpenETAPIBaseUrl: "https://openet.dri.edu"
  OpenETRasterTimeSeriesMultipolygonRoute: "raster/timeseries/multipolygon"
  OpenETRasterMetadataRoute: "raster/metadata"
  OpenETAllFilesReadyForExportRoute: "raster/export/all_files"
  OpenETRasterExportStatusRoute: "raster/export/status"
  OpenETShapefilePath: "users/wicarrara/all_parcels_edf"
  OpenETRasterTimeseriesMultipolygonColumnToUseAsIdentifier: "ParcelNumb"
  ParcelBoundingBoxLeft: "-119.45272037350193"
  ParcelBoundingBoxRight: "-119.11015104115182"
  ParcelBoundingBoxTop: "35.442022035628575"
  ParcelBoundingBoxBottom: "35.27608156273151"
  datadogClientToken: "pub083a61c0ce87f2d49aff26114600b3e4"
{{ end }}