apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rio-api.fullname" . }}-prod-configmap
data:
  SECRET_PATH: "/app/secrets/rioApiSecrets"
  DOCKER_BUILD_SOURCE: "."
  ASPNETCORE_ENVIRONMENT: "Production"
  KEYSTONE_HOST: "https://identity.sitkatech.com"
  SITKA_EMAIL_REDIRECT: ""
  WEB_URL: "https://{{ .Values.global.domains.web }}"
  KEYSTONE_REDIRECT_URL: "https://{{ .Values.global.domains.web }}/create-user-callback"
  APPINSIGHTS_INSTRUMENTATIONKEY: "{{ .Values.global.env.appInsightsInstrumentationKey }}"
  ALLOW_TRADING: "{{ .Values.global.env.allowTrading }}"
  PlatformLongName: "{{ .Values.global.env.platformLongName }}"
  PlatformShortName: "{{ .Values.global.env.platformShortName }}"
  LeadOrganizationLongName: "{{ .Values.global.env.leadOrganizationLongName }}"
  LeadOrganizationShortName: "{{ .Values.global.env.leadOrganizationShortName }}"
  LeadOrganizationHomeUrl: "{{ .Values.global.env.leadOrganizationHomeUrl }}"
  LeadOrganizationEmail: "{{ .Values.global.env.leadOrganizationEmail }}"
  VerificationKeyChars: "ABCDEFGHIJKLMNOPQRSTUVWXYZ,0123456789"
  ValidParcelNumberRegexPattern: "^[0-9]{3}-[0-9]{3}-[0-9]{2}$$"
  ValidParcelNumberPatternAsStringForDisplay: "###-##-###"
  OpenETAPIBaseUrl: "https://openet.dri.edu"
  OpenETRasterTimeSeriesMultipolygonRoute: "raster/timeseries/multipolygon"
  OpenETRasterMetadataRoute: "raster/metadata"
  OpenETAllFilesReadyForExportRoute: "raster/export/all_files"
  OpenETRasterExportStatusRoute: "raster/export/status"
  OpenETRasterMetadataBoundingBoxLeft: "{{ .Values.global.env.openETRasterMetadataBoundingBoxLeft }}"
  OpenETRasterMetadataBoundingBoxRight: "{{ .Values.global.env.openETRasterMetadataBoundingBoxRight }}"
  OpenETRasterMetadataBoundingBoxTop: "{{ .Values.global.env.openETRasterMetadataBoundingBoxTop }}"
  OpenETRasterMetadataBoundingBoxBottom: "{{ .Values.global.env.openETRasterMetadataBoundingBoxBottom }}"
  OpenETRasterTimeseriesMultipolygonColumnToUseAsIdentifier: "{{ .Values.global.env.openETRasterTimeseriesMultipolygonColumnToUseAsIdentifier }}"
  AllowOpenETSync: "{{ .Values.global.env.allowOpenETSync }}"
  Ogr2OgrExecutable: "/usr/bin/ogr2ogr"
  OgrInfoExecutable: "/usr/bin/ogrinfo"
