{{ if eq .Values.global.env.name "prod" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rio-api.fullname" . }}-prod-configmap
data:
  SECRET_PATH: "/app/secrets/rioApiSecrets"
  DOCKER_BUILD_SOURCE: "."
  ASPNETCORE_ENVIRONMENT: "Production"
  KEYSTONE_HOST: "https://identity.sitkatech.com"
  SITKA_EMAIL_REDIRECT: ""
  WEB_URL: "https://{{ .Values.global.domains.web }}"
  KEYSTONE_REDIRECT_URL: "https://{{ .Values.global.domains.web }}/create-user-callback"
  APPINSIGHTS_INSTRUMENTATIONKEY: "{{ .Values.global.env.appInsightsInstrumentationKey }}"
  Ogr2OgrExecutable: "/usr/bin/ogr2ogr"
  OgrInfoExecutable: "/usr/bin/ogrinfo"
{{ end }}