apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rio-api.fullname" . }}-rio-rrb-configmap
data:
  AllowTrading: "false"
  AllowOpenETSync: "true"
  IncludeWaterSupply: "true"
  PlatformLongName: "Rosedale-Rio Bravo Water Accounting Platform"
  PlatformShortName: "Water Accounting Platform"
  LeadOrganizationLongName: "Rosedale-Rio Bravo Water Storage District"
  LeadOrganizationShortName: "RRB"
  LeadOrganizationHomeUrl: "https://rrbwsd.com"
  LeadOrganizationEmail: "admin@rrbwsd.com"
  VerificationKeyChars: "ABCDEFGHIJKLMNOPQRSTUVWXYZ,0123456789"
  ValidParcelNumberRegexPattern: "^[0-9]{3}-[0-9]{3}-[0-9]{2}$$"
  ValidParcelNumberPatternAsStringForDisplay: "###-###-##"
  OpenETAPIBaseUrl: "https://openet.dri.edu"
  OpenETRasterTimeSeriesMultipolygonRoute: "raster/timeseries/multipolygon"
  OpenETRasterMetadataRoute: "raster/metadata"
  OpenETAllFilesReadyForExportRoute: "raster/export/all_files"
  OpenETRasterExportStatusRoute: "raster/export/status"
  OpenETShapefilePath: "users/wicarrara/RRBWSD_2020_parcels"
  OpenETRasterTimeseriesMultipolygonColumnToUseAsIdentifier: "APN_LABEL"
  ParcelBoundingBoxLeft: "-119.45272037350193"
  ParcelBoundingBoxRight: "-119.11015104115182"
  ParcelBoundingBoxTop: "35.442022035628575"
  ParcelBoundingBoxBottom: "35.27608156273151"
