apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rio-api.fullname" . }}
  labels:
    {{- include "rio-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "rio-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }} # roll deployments on every upgrade: https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rio-api.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
      - name: secrets
        secret:
          secretName: rio-{{ .Values.global.env.tenantName }}-api-secrets
      # - name: certs
      #   hostPath:
      #     # directory location on host
      #     path: /run/desktop/mnt/host/c/Users/stewart.gordon/.aspnet/https
      #     # this field is optional
      #     type: Directory
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rio-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.global.env.name }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     scheme: HTTPS
          #     port: 443
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     scheme: HTTPS
          #     port: 443
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
          - configMapRef:
              name: {{ include "rio-api.fullname" . }}-{{ .Values.global.env.name }}-configmap
          volumeMounts:
          - name: secrets
            mountPath: /app/secrets
            readOnly: true
          # - name: certs
          #   mountPath: /https
          #   readOnly: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
