apiVersion: v1
kind: Secret
metadata:
  name: rio-{{ .Values.global.env.tenantName }}-api-secrets
type: Opaque
stringData:
  rioApiSecrets: |
    {
      "DB_CONNECTION_STRING": "Data Source={{ .Values.global.env.dbServer }};Initial Catalog={{ .Values.global.env.databaseName }};Persist Security Info=True;User ID={{ .Values.global.env.sqlUsername }};Password={{ .Values.global.secrets.apiSqlPassword }}",
      "HangfireUserName": "{{ .Values.global.secrets.hangfireUserName }}",
      "HangfirePassword": "{{ .Values.global.secrets.hangfirePassword }}",
      "SendGridApiKey": "{{ .Values.global.secrets.sendGridApiKey }}",
      "OpenETAPIKey": "{{ .Values.global.secrets.openETApiKey }}",
    }