apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      #nodePort: 30080
      targetPort: http
      protocol: TCP
      name: http
    # - port: 443
    #   #nodePort: 30443
    #   targetPort: https
    #   protocol: TCP
    #   name: https
  selector:
    {{- include "api.selectorLabels" . | nindent 4 }}
