apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "geoserver.fullname" . }}-configmap
data:
  ENABLE_JSONP: "true"
  CATALINA_OPTS: "-DALLOW_ENV_PARAMETRIZATION=true"
  ENV_PROPERTIES: "/app/config/geoserver-environment.properties"
  STABLE_EXTENSIONS: "sqlserver-plugin"
  TOMCAT_EXTRAS: "false"
  ROOT_WEBAPP_REDIRECT: "true"
  SAMPLE_DATA: "false"
  HTTP_PROXY_NAME: "{{ .Values.global.domains.geoserver }}"
  HTTP_SCHEME: "https"
  GEOSERVER_ADMIN_USER: "geomaster"
  GEOSERVER_ADMIN_PASSWORD_FILE: "/app/secrets/geoserverAdminPassword"
  INITIAL_MEMORY: "1G"
  MAXIMUM_MEMORY: "2G"