apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "geoserver.fullname" . }}-environment-properties-configmap
data:
  geoserver-environment.properties: |
    datastore-host = {{ .Values.global.env.dbServer }}
    datastore-database = {{ .Values.global.env.databaseName }}
    datastore-user = {{ .Values.global.env.sqlGeoserverUsername }}
    datastore-password = {{ .Values.global.secrets.geoserverSqlServerPassword }}