apiVersion: v1
kind: Secret
metadata:
  name: rio-{{ .Values.global.env.tenantName }}-geoserver-volume-secret
type: Opaque
data:
  azurestorageaccountname: {{ .Values.global.secrets.geoserverAzureStorageAccountName | b64enc }}
  azurestorageaccountkey: {{ .Values.global.secrets.geoserverAzureStorageAccountKey | b64enc }}