SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[WaterYearMonth](
	[WaterYearMonthID] [int] IDENTITY(1,1) NOT NULL,
	[WaterYearID] [int] NOT NULL,
	[Month] [int] NOT NULL,
	[FinalizeDate] [datetime] NULL,
 CONSTRAINT [PK_WaterYearMonth_WaterYearMonthID] PRIMARY KEY CLUSTERED 
(
	[WaterYearMonthID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_WaterYearMonth_WaterYearID_Month] UNIQUE NONCLUSTERED 
(
	[WaterYearID] ASC,
	[Month] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[WaterYearMonth]  WITH CHECK ADD  CONSTRAINT [FK_WaterYearMonth_WaterYear_WaterYearID] FOREIGN KEY([WaterYearID])
REFERENCES [dbo].[WaterYear] ([WaterYearID])
GO
ALTER TABLE [dbo].[WaterYearMonth] CHECK CONSTRAINT [FK_WaterYearMonth_WaterYear_WaterYearID]