SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ParcelTag](
	[ParcelTagID] [int] IDENTITY(1,1) NOT NULL,
	[ParcelID] [int] NOT NULL,
	[TagID] [int] NOT NULL,
 CONSTRAINT [PK_ParcelTag_ParcelTagID] PRIMARY KEY CLUSTERED 
(
	[ParcelTagID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[ParcelTag]  WITH CHECK ADD  CONSTRAINT [FK_ParcelTag_Parcel_ParcelID] FOREIGN KEY([ParcelID])
REFERENCES [dbo].[Parcel] ([ParcelID])
GO
ALTER TABLE [dbo].[ParcelTag] CHECK CONSTRAINT [FK_ParcelTag_Parcel_ParcelID]
GO
ALTER TABLE [dbo].[ParcelTag]  WITH CHECK ADD  CONSTRAINT [FK_ParcelTag_Tag_TagID] FOREIGN KEY([TagID])
REFERENCES [dbo].[Tag] ([TagID])
GO
ALTER TABLE [dbo].[ParcelTag] CHECK CONSTRAINT [FK_ParcelTag_Tag_TagID]