SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[WaterYear](
	[WaterYearID] [int] IDENTITY(1,1) NOT NULL,
	[Year] [int] NOT NULL,
	[FinalizeDate] [datetime] NULL,
	[ParcelLayerUpdateDate] [datetime] NULL,
 CONSTRAINT [PK_WaterYear_WaterYearID] PRIMARY KEY CLUSTERED 
(
	[WaterYearID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [AK_WaterYear_Year] UNIQUE NONCLUSTERED 
(
	[Year] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
