apiVersion: v1
kind: Secret
metadata:
  name: rio-rrb-api-secrets
type: Opaque
stringData:
  rio-rrbApiSecrets: |
    {
      "DB_CONNECTION_STRING": "Data Source={{ .Values.global.env.dbServer }};Initial Catalog={{ .Values.global.env.databaseName }};Persist Security Info=True;User ID={{ .Values.global.env.sqlUsername }};Password={{ .Values.global.secrets.apiSqlPassword }}",
      "HangfireUserName": "HangfireAdmin",
      "HangfirePassword": "password",
      "SendGridApiKey": "{{ .Values.global.secrets.sendGridApiKey }}"
    }