apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rio-edf-web.fullname" . }}-prod-configmap
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  Production: "true"
  Staging: "false"
  Dev: "false"
  MainAppApiUrl: "https://{{ .Values.global.domains.api }}"
  CreateAccountRedirectUrl: "https://{{ .Values.global.domains.web }}/create-user-callback"
  AllowTrading: "true"
  AllowOpenETSync: "true"
  KeystoneSupportBaseUrl: "https://identity.sitkatech.com/Authentication"
  GeoserverMapServiceUrl: "https://{{ .Values.global.domains.geoserver }}/geoserver/Rio"
  Keystone_ClientID: "RioEDF"
  Keystone_Issuer: "https://identity.sitkatech.com"
  Keystone_RedirectUriRelative: "/signin-oidc"
  Keystone_Scope: "openid profile offline_access keystone"
  Keystone_SessionCheckEnabled: "false"
  Keystone_LogoutUrl: "https://identity.sitkatech.com/account/logout"
  Keystone_PostLogoutRedirectUri: "/"
  Keystone_WaitForTokenInMsec: "500"
  Keystone_ResponseType: "code"
  Keystone_DisablePKCE: "false"
  PlatformLongName: "Water Accounting and Trading Platform"
  PlatformShortName: "Water Accounting and Trading Platform"
  LeadOrganizationLongName: "Environmental Defense Fund"
  LeadOrganizationShortName: "EDF"
  LeadOrganizationHomeUrl: "https://www.edf.org/"
  FaviconFilename: "edf_favicon.ico"
  LeadOrganizationLogoFilename: "edf-full-logo.jpg"
  ContactInfoPhone: "415-293-6088"
  ContactInfoEmail: "cbabbitt@edf.org"
  ContactInfoMailingAddress: ""
  ContactInfoPhysicalAddress: ""
  EnabledGETIntegration: "true"
  NavThemeColor: "light"
  ApplicationInternalName: "RioEDF"
